### ISSUE TITLE
Unable to install with react 17.0.2

### ISSUE THREAD

**Issue by digz6666** [ShaMan123/react-math-view#2]
When installing with npm, it says:

```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-math-view@1.2.0
npm ERR! node_modules/react-math-view
npm ERR!   react-math-view@"*" from the root project
```

**Comment by ShaMan123** [comment]
try this patch c21987b

**Comment by digz6666** [comment]
> try this patch [c21987b](https://github.com/ShaMan123/react-math-view/commit/c21987b4fefea7340b3e704895b02f92bf8de702)

Thanks, I will try it!

**Comment by digz6666** [comment]
> try this patch [c21987b](https://github.com/ShaMan123/react-math-view/commit/c21987b4fefea7340b3e704895b02f92bf8de702)

It works!
