### ISSUE TITLE
White space is added at the bottom of the screen - MathLive autocomplete

### ISSUE THREAD

**Issue by juan-lemos** [ShaMan123/react-math-view#3]
**Describe the bug**
White space is added at the bottom of the screen where appear the math text input

**To Reproduce**
1. screen with math input 
2. at the bottom there is a white space

**Expected behavior**
No white space at the bottom

**Screenshots**
<img width="912" alt="Screen Shot 2021-03-30 at 7 38 27 PM" src="https://user-images.githubusercontent.com/20597175/113066575-1eebfe00-9191-11eb-8b8a-1bb51740b52f.png">

**Desktop (please complete the following information):**
 - OS: os x
 - Browser chrome
 - Version: 1.2.0

**Additional context**
You can experience this issue on this testing repository.
https://github.com/juanpale/testMathLibrary

**Comment by ShaMan123** [comment]
Hi,
Missed this issue by mistake.
Could you open a codesandbox?

**Comment by juan-lemos** [comment]
Hi, @ShaMan123 
Share with you the link [https://codesandbox.io/s/github/juanpale/testMathLibrary](https://codesandbox.io/s/github/juanpale/testMathLibrary).
You can play with the next button that makes the input appear or disappear.

Thank you for your help!

**Comment by ShaMan123** [comment]
I don't understand what should and shouldn't happen

**Comment by ShaMan123** [comment]
I am guessing it's the auto complete that tries to pop up.
Haven't addressed that part.

**Comment by juan-lemos** [comment]
Hi, @ShaMan123 what I was trying to explain is that white space that is created at the bottom (photo below), when the react-math-view is rendered. When is not render it disappears. 
You can check this by pressing the next button that stops rendering the react-math-view.
<img width="658" alt="Screen Shot 2021-05-13 at 2 36 26 PM" src="https://user-images.githubusercontent.com/20597175/118163693-abc4e100-b3f8-11eb-8817-13fcb39fb9f0.png">

**Comment by ShaMan123** [comment]
You can see in the console that these are the elements that produce the white space:
```html
<div aria-hidden="true" data-refcount="1" class="ML__popover" id="mathlive-popover-panel"></div>
<div aria-hidden="true" data-refcount="1" class="ML__keystroke-caption" id="mathlive-keystroke-caption-panel"></div>
```
So my guess was correct.
> I am guessing it's the auto complete that tries to pop up.
> Haven't addressed that part.

I need to address this.
As a workaround simply override the css in your files:
```css
.ML__popover {
   display: none !important;
}
.ML__keystroke-caption {
   display: none !important;
}

```

**Comment by ShaMan123** [comment]
https://github.com/arnog/mathlive/blob/50f78d61357b02f7ba947a3ab9506199af1c6465/src/editor/popover.ts#L451

https://github.com/arnog/mathlive/blob/50f78d61357b02f7ba947a3ab9506199af1c6465/src/editor/popover.ts#L305
